---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
          - name: create a security group
            ec2_group:
                    name: web-app
                    description: "Sec group for app"
                    region: ap-south-1
                    rules:
                            - proto: tcp
                              ports:
                                      - 22
                              cidr_ip: 0.0.0.0/0

            register: result_sec_group
          - name: Provision instance(s)
            ec2:
                    key_name: ansible-key
                    image: ami-0b44050b2d893d5f7
                    instance_type: t2.micro
                    group_id: "{{ result_sec_group.group_id }}"
                    region: ap-south-1
                    count_tag:
                            Name: apacheserver
                    wait: true
                    count: 1

