---
 - name: Play for Wordpress
   hosts: slave
   become: yes
   gather_facts: false
   tasks:
           - name: To install apache packages
             apt:
                     name: apache2
                     state: present
                     update_cache: yes
           - name: To install php
             apt:
                     name: php
                     state: present
                     update_cache: yes

           - name: To install php-mysql extension
             apt:
                     name: php-mysql
                     state: present
                     update_cache: yes
           
           - name: To start the apache service
             service:
                     name: apache2
                     state: started
                     enabled: yes

           - name: To download wordpress URL
             get_url:
                     url: https://wordpress.org/latest.tar.gz
                     dest: /var/www/html/latest.tar.gz
                     mode: '0775'
           - name: To remove by default index.html
             shell: rm -rf /var/www/html/index.html

           - name: Extract latest.tar.gz
             unarchive:
                     src: /var/www/html/latest.tar.gz
                     dest: /var/www/html
                     remote_src: yes
           
           - name: Some Modifications required
             shell: rm -rf /var/www/html/latest.tar.gz; mv /var/www/html/wordpress/* /var/www/html/; chmod -R 775 /var/www/html/; chown -R www-data:www-data /var/www/html/
           - name: Restart the apache2 services
             service:
                     name: apache2
                     state: restarted
